### ISSUE TITLE
Scrolling text area bleeds through rounded corners

### ISSUE THREAD

**Issue by Exalm** [gi-lom/dialect#49]
![Screenshot from 2020-10-16 03-22-45](https://user-images.githubusercontent.com/1510457/96192172-e6e45c00-0f5e-11eb-90e2-085efa6abc0a.png)

Fixing this in a generic way is pretty complex, but what you can do is:

1. Have margins on your text view, so that its background doesn't extend to the leftmost/rightmost 6px or however big your border-radius is;
2. Round the scrollbar in css (don't forget about rtl though)

**Comment by Exalm** [comment]
Looks like you still forgot scrollbars :)

**Comment by Exalm** [comment]
Do sth like:

```css
.translation-frame scrollbar {
  padding-top: 3px;
}

.translation-frame scrollbar:dir(ltr) {
  border-top-right-radius: 9px;
}

.translation-frame scrollbar:dir(rtl) {
  border-top-left-radius: 9px;
}
```
